In [1]:
import pandas as pd
import requests
import json
import datetime
import edgar_funcs as ef

In [2]:
ticker = "MSFT"

In [3]:
facts = ef.get_facts_for_ticker(ticker)

In [4]:
ten_Qs = ef.get_10Q_filings_for_ticker(ticker)
ten_Qs['reportDate'] = pd.to_datetime(ten_Qs['reportDate'])
ten_Qs.set_index('reportDate', inplace=True)
ten_Q_accessionNumbers = ten_Qs['accessionNumber']
ten_Q_accessionNumbers.name = 'ten_Q_accessionNumber'

In [5]:
ten_Ks = ef.get_10K_filings_for_ticker(ticker)
ten_Ks['reportDate'] = pd.to_datetime(ten_Ks['reportDate'])
ten_Ks.set_index('reportDate', inplace=True)
ten_K_accessionNumbers = ten_Ks['accessionNumber']
ten_K_accessionNumbers.name = 'ten_K_accessionNumber'

In [6]:
ten_Qs

,accessionNumber,filingDate,acceptanceDateTime,act,form,fileNumber,filmNumber,items,size,isXBRL,isInlineXBRL,primaryDocument,primaryDocDescription
reportDate,,,,,,,,,,,,,
2023-03-31,0000950170-23-014423,2023-04-25,2023-04-25T16:07:43.000Z,34,10-Q,001-37845,23844923,,32928186,1,1,msft-20230331.htm,10-Q
2022-12-31,0001564590-23-000733,2023-01-24,2023-01-24T16:34:20.000Z,34,10-Q,001-37845,23548555,,22217673,1,1,msft-10q_20221231.htm,10-Q
2022-09-30,0001564590-22-035087,2022-10-25,2022-10-25T16:08:55.000Z,34,10-Q,001-37845,221329593,,18509528,1,1,msft-10q_20220930.htm,10-Q
2022-03-31,0001564590-22-015675,2022-04-26,2022-04-26T16:08:55.000Z,34,10-Q,001-37845,22854390,,22314465,1,1,msft-10q_20220331.htm,10-Q
2021-12-31,0001564590-22-002324,2022-01-25,2022-01-25T16:09:04.000Z,34,10-Q,001-37845,22554019,,21933276,1,1,msft-10q_20211231.htm,10-Q
2021-09-30,0001564590-21-051992,2021-10-26,2021-10-26T16:11:30.000Z,34,10-Q,001-37845,211348546,,18484545,1,1,msft-10q_20210930.htm,10-Q
2021-03-31,0001564590-21-020891,2021-04-27,2021-04-27T16:09:38.000Z,34,10-Q,001-37845,21859007,,22586167,1,1,msft-10q_20210331.htm,10-Q
2020-12-31,0001564590-21-002316,2021-01-26,2021-01-26T16:09:34.000Z,34,10-Q,001-37845,21554140,,21735875,1,1,msft-10q_20201231.htm,10-Q
2020-09-30,0001564590-20-047996,2020-10-27,2020-10-27T16:21:58.000Z,34,10-Q,001-37845,201264355,,18132017,1,1,msft-10q_20200930.htm,10-Q
2020-03-31,0001564590-20-019706,2020-04-29,2020-04-29T16:11:11.000Z,34,10-Q,001-37845,20830395,,21306500,1,1,msft-10q_20200331.htm,10-Q
2019-12-31,0001564590-20-002450,2020-01-29,2020-01-29T16:08:43.000Z,34,10-Q,001-37845,20558255,,21244567,1,1,msft-10q_20191231.htm,10-Q
2019-09-30,0001564590-19-037549,2019-10-23,2019-10-23T16:09:48.000Z,34,10-Q,001-37845,191163879,,17515373,1,1,msft-10q_20190930.htm,10-Q
2019-03-31,0001564590-19-012709,2019-04-24,2019-04-24T16:10:10.000Z,34,10-Q,001-37845,19763948,,19897404,1,0,msft-10q_20190331.htm,10-Q
2018-12-31,0001564590-19-001392,2019-01-30,2019-01-30T16:09:56.000Z,34,10-Q,001-37845,19552047,,19829376,1,0,msft-10q_20181231.htm,10-Q
2018-09-30,0001564590-18-024893,2018-10-24,2018-10-24T16:13:07.000Z,34,10-Q,001-37845,181136518,,16227025,1,0,msft-10q_20180930.htm,10-Q
2018-03-31,0001564590-18-009307,2018-04-26,2018-04-26T16:10:21.000Z,34,10-Q,001-37845,18778616,,24603474,1,0,msft-10q_20180331.htm,10-Q
2017-12-31,0001564590-18-001129,2018-01-31,2018-01-31T16:10:10.000Z,34,10-Q,001-37845,18562797,,24083544,1,0,msft-10q_20171231.htm,10-Q
2017-09-30,0001564590-17-020171,2017-10-26,2017-10-26T16:08:58.000Z,34,10-Q,001-37845,171156404,,20542973,1,0,msft-10q_20170930.htm,10-Q
2017-03-31,0001564590-17-007547,2017-04-27,2017-04-27T16:16:04.000Z,34,10-Q,001-37845,17789272,,21250379,1,0,msft-10q_20170331.htm,10-Q
2016-12-31,0001564590-17-000654,2017-01-26,2017-01-26T16:13:28.000Z,34,10-Q,001-37845,17549845,,20484900,1,0,msft-10q_20161231.htm,10-Q

In [7]:
combined_accessionNumbers_for_filter = pd.concat([ten_Q_accessionNumbers, ten_K_accessionNumbers], join='outer' )
print(ten_Q_accessionNumbers.head())
print(ten_K_accessionNumbers.head())

reportDate
2023-03-31    0000950170-23-014423
2022-12-31    0001564590-23-000733
2022-09-30    0001564590-22-035087
2022-03-31    0001564590-22-015675
2021-12-31    0001564590-22-002324
Name: ten_Q_accessionNumber, dtype: object
reportDate
2022-06-30    0001564590-22-026876
2021-06-30    0001564590-21-039151
2020-06-30    0001564590-20-034944
2019-06-30    0001564590-19-027952
2018-06-30    0001564590-18-019062
Name: ten_K_accessionNumber, dtype: object

In [8]:
df = facts.T
df.index.name = 'fact'
df.set_index(['label', 'description'], append=True, inplace=True)
df.head()

                                                                                                                                                                                   units
fact                            label                                              description
AccountsPayableCurrent          Accounts Payable, Current                          Carrying value as of the balance sheet date of ...  {'USD': [{'end': '2009-06-30', 'val': 33240000...
AccountsReceivableNet           Accounts Receivable, after Allowance for Credit... Amount, after allowance for credit loss, of rig...  {'USD': [{'end': '2016-07-01', 'val': 22300000...
AccountsReceivableNetCurrent    Accounts Receivable, after Allowance for Credit... Amount, after allowance for credit loss, of rig...  {'USD': [{'end': '2009-06-30', 'val': 11192000...
AccountsReceivableNetNoncurrent Accounts Receivable, after Allowance for Credit... Amount, after allowance for credit loss, of rig...  {'USD': [{'end': '2017-06-30', 'val': 17000000...
AccruedIncomeTaxesCurrent       Accrued Income Taxes, Current                      Carrying amount as of the balance sheet date of...  {'USD': [{'end': '2009-06-30', 'val': 72500000...

In [9]:
units_df = facts.T
units_df = units_df['units']
units_df.head()

fact
AccountsPayableCurrent             {'USD': [{'end': '2009-06-30', 'val': 33240000...
AccountsReceivableNet              {'USD': [{'end': '2016-07-01', 'val': 22300000...
AccountsReceivableNetCurrent       {'USD': [{'end': '2009-06-30', 'val': 11192000...
AccountsReceivableNetNoncurrent    {'USD': [{'end': '2017-06-30', 'val': 17000000...
AccruedIncomeTaxesCurrent          {'USD': [{'end': '2009-06-30', 'val': 72500000...
Name: units, dtype: object

In [10]:
units_dict = units_df.to_dict()
units_expanded_df = pd.DataFrame()

In [11]:
units_expanded_df['fact'] = units_dict.keys()

In [12]:
# for key in units_dict.items():
#    for unit in key[1]:
#       units_expanded_df.loc[units_expanded_df['fact'] == key[0], 'unit'] = unit

In [13]:
# for account_key, account_value in units_dict.items():
#     for unit_key, unit_value in account_value.items():
#         for dictionary in unit_value:
#             for key, value in dictionary.items():
#                 print(f"Account key: {account_key}, unit key: {unit_key}, Key in dictionary: {key}, Value in dictionary: {value}")

In [14]:
units_expanded_df

                                                  fact
0                               AccountsPayableCurrent
1                                AccountsReceivableNet
2                         AccountsReceivableNetCurrent
3                      AccountsReceivableNetNoncurrent
4                            AccruedIncomeTaxesCurrent
..                                                 ...
531    EffectiveIncomeTaxRateReconciliationFdiiPercent
532  EffectOfExchangeRateOnCashCashEquivalentsRestr...
533              LossContingencyAccrualAtCarryingValue
534                                    SeveranceCosts1
535  RestructuringAndRelatedCostExpectedNumberOfPos...

[536 rows x 1 columns]

In [15]:
def explore_dict(data):
    rows = []

    for account_key, account_values in data.items():
        for unit_key, unit_values in account_values.items():
            for item in unit_values:
                row = {"account_key": account_key, "unit_key": unit_key}
                row.update(item)
                rows.append(row)

    df = pd.DataFrame(rows)
    return df

In [16]:
test_df = explore_dict(units_dict)
test2_df = test_df[test_df['accn'].isin(combined_accessionNumbers_for_filter)].dropna(subset=['frame'])

In [17]:
test3_df = test2_df.drop(['accn', 'start', 'fy', 'fp', 'frame', 'filed', 'form'], axis=1)
test3_df['fact__unit'] = test3_df['account_key'] + '__' + test3_df['unit_key']
test3_df = test3_df.drop(['account_key', 'unit_key'], axis=1)

In [18]:
test3_df

,end,val,fact__unit
63,2016-06-30,6.898000e+09,AccountsPayableCurrent__USD
65,2016-12-31,6.580000e+09,AccountsPayableCurrent__USD
66,2017-03-31,6.217000e+09,AccountsPayableCurrent__USD
71,2017-06-30,7.390000e+09,AccountsPayableCurrent__USD
72,2017-09-30,6.866000e+09,AccountsPayableCurrent__USD
...,...,...,...
25759,2022-09-30,2.640000e+08,LossContingencyAccrualAtCarryingValue__USD
25760,2022-12-31,1.810000e+08,LossContingencyAccrualAtCarryingValue__USD
25761,2023-03-31,1.770000e+08,LossContingencyAccrualAtCarryingValue__USD
25763,2022-12-31,8.000000e+08,SeveranceCosts1__USD
25764,2023-01-18,1.000000e+04,RestructuringAndRelatedCostExpectedNumberOfPos...

In [19]:
combined_accessionNumbers_for_filter

reportDate
2023-03-31    0000950170-23-014423
2022-12-31    0001564590-23-000733
2022-09-30    0001564590-22-035087
2022-03-31    0001564590-22-015675
2021-12-31    0001564590-22-002324
2021-09-30    0001564590-21-051992
2021-03-31    0001564590-21-020891
2020-12-31    0001564590-21-002316
2020-09-30    0001564590-20-047996
2020-03-31    0001564590-20-019706
2019-12-31    0001564590-20-002450
2019-09-30    0001564590-19-037549
2019-03-31    0001564590-19-012709
2018-12-31    0001564590-19-001392
2018-09-30    0001564590-18-024893
2018-03-31    0001564590-18-009307
2017-12-31    0001564590-18-001129
2017-09-30    0001564590-17-020171
2017-03-31    0001564590-17-007547
2016-12-31    0001564590-17-000654
2022-06-30    0001564590-22-026876
2021-06-30    0001564590-21-039151
2020-06-30    0001564590-20-034944
2019-06-30    0001564590-19-027952
2018-06-30    0001564590-18-019062
2017-06-30    0001564590-17-014900
dtype: object

In [20]:
pivot_df = test3_df.pivot_table(index='end', columns='fact__unit', values='val', aggfunc='first')
pivot_df.index = pd.to_datetime(pivot_df.index)
pivot_df_recent= pivot_df[pivot_df.index.isin(combined_accessionNumbers_for_filter.index)]
pivot_df_recent = pivot_df_recent.dropna(axis=1, how='all')
for col in pivot_df_recent.columns:
    if '_USD' in col or '_shares' in col and pivot_df_recent[col].abs().max() > 1_000:
        pivot_df_recent[col] = pivot_df_recent[col] / 1_000_000
        pivot_df_recent.rename(columns={col: col + '(millions)'}, inplace=True)
pivot_df_recent = pivot_df_recent.T
pivot_df_recent.name = ticker
pivot_df_recent

end,2016-12-31,2017-03-31,2017-06-30,2017-09-30,2017-12-31,2018-03-31,2018-06-30,2018-09-30,2018-12-31,2019-03-31,...,2020-12-31,2021-03-31,2021-06-30,2021-09-30,2021-12-31,2022-03-31,2022-06-30,2022-09-30,2022-12-31,2023-03-31
fact__unit,,,,,,,,,,,,,,,,,,,,,
AccountsPayableCurrent__USD(millions),6580.0,6217.0,7390.0,6866.0,7850.0,7623.0,8617.0,8511.0,7563.0,7544.0,...,12770.0,13412.0,15163.0,14832.0,15314.0,16085.0,19000.0,16609.0,15354.0,15305.0
AccountsReceivableNetCurrent__USD(millions),14343.0,12882.0,22431.0,14561.0,18428.0,17208.0,26481.0,17390.0,19680.0,19269.0,...,27312.0,26322.0,38043.0,27349.0,33520.0,32613.0,44261.0,31279.0,35833.0,37420.0
AccountsReceivableNetNoncurrent__USD(millions),NaN,NaN,1700.0,1600.0,1600.0,1600.0,1800.0,1800.0,1900.0,2000.0,...,2900.0,2800.0,3400.0,3400.0,3500.0,3600.0,3800.0,3800.0,4200.0,4300.0
AccruedIncomeTaxesCurrent__USD(millions),508.0,654.0,718.0,920.0,788.0,814.0,2121.0,2341.0,2033.0,1950.0,...,1562.0,2165.0,2174.0,6272.0,3731.0,4646.0,4067.0,6729.0,3553.0,4163.0
AccruedIncomeTaxesNoncurrent__USD(millions),13300.0,14400.0,13485.0,13944.0,30050.0,30669.0,30265.0,28936.0,29161.0,29514.0,...,26701.0,27157.0,27190.0,25715.0,26121.0,26483.0,26069.0,23712.0,24169.0,25000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
UnrecognizedTaxBenefitsReductionsResultingFromLapseOfApplicableStatuteOfLimitations__USD(millions),NaN,NaN,48.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
UnrecognizedTaxBenefitsThatWouldImpactEffectiveTaxRate__USD(millions),NaN,NaN,10200.0,NaN,NaN,NaN,11300.0,NaN,NaN,NaN,...,NaN,NaN,12500.0,NaN,NaN,NaN,13300.0,NaN,NaN,NaN
UnrecognizedTaxBenefits__USD(millions),NaN,NaN,11737.0,NaN,NaN,NaN,11961.0,NaN,NaN,NaN,...,NaN,NaN,14550.0,NaN,NaN,NaN,15593.0,NaN,NaN,NaN
WeightedAverageNumberOfDilutedSharesOutstanding__shares(millions),7830.0,7813.0,7832.0,7799.0,7710.0,7794.0,7794.0,7766.0,7768.0,7744.0,...,7616.0,7597.0,7608.0,7567.0,7555.0,7534.0,7540.0,7485.0,7473.0,7464.0
WeightedAverageNumberOfSharesOutstandingBasic__shares(millions),7755.0,7725.0,7746.0,7708.0,7710.0,7698.0,7700.0,7673.0,7692.0,7672.0,...,7555.0,7539.0,7547.0,7513.0,7505.0,7493.0,7496.0,7457.0,7451.0,7441.0